package:
  name: acpype
  version: "2019.07.02.16.09"

source:
  git_rev: "recipe"
  git_url: https://github.com/alanwilter/acpype.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openbabel
    - ambertools

test:
  commands:
    - acpype -h

about:
  home: https://github.com/alanwilter/acpype
  license: GPL3
  license_file: LICENSE
