{% set data = load_setup_py_data() %}
{% set version = data.get('version')  %}

package:
  name: acpype
  version: {{ version }}

source:
  git_url: https://github.com/alanwilter/acpype.git
  git_tag: fix_version

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openbabel
    - ambertools

test:
  commands:
    - acpype -v

about:
  home: https://github.com/alanwilter/acpype
  license: GPL3
  license_file: LICENSE
