# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: check_acpype_api
on:
   push:
      branches:
      - master
      - new_functions
   pull_request:
      branches:
      - master
      - new_functions
jobs:
   build:
      runs-on: ubuntu-latest
      steps:

      -  uses: actions/checkout@v2

      -  name: Set up Python 3.8
         uses: actions/setup-python@v2
         with:
            python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
            # This path is specific to Ubuntu
            path: ~/.cache/pip
            # Look to see if there is a cache hit for the corresponding requirements file
            key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
            restore-keys: |
               ${{ runner.os }}-pip-
               ${{ runner.os }}-

      - name: Install dependencies
        run: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
            apt-get install --no-install-recommends -y openbabel python3-openbabel python3-pip
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            chmod +x /home/acpype_lib/acpype.py
            ln -s /home/acpype_lib/acpype.py /usr/local/bin/acpype
            export AMBERHOME=/home/amber19-0_linux
            export PATH=$PATH:$AMBERHOME/bin

      -  name: Lint with flake8
         run: flake8 -v --count

      -  name: Check format with black
         run: black --diff --check .

      -  name: Test with PyTest
         run: pytest --color=yes
